services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "8.2"
    container_name: website
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - storage_data:/var/www/html/storage
      - temp_data:/var/www/html/temp
      - uploads_data:/var/www/html/protect/uploads
    restart: unless-stopped

volumes:
  storage_data:
  temp_data:
  uploads_data:
